name: Publish Module

on:
    workflow_call:
        inputs:
            version:
                type: string
                required: true
            build_timestamp:
                type: string
                required: true
            release_type:
                type: string
                required: false
                default: release

            module:
                type: string
                required: true
            modules_json:
                type: string
                required: true

jobs:
    extract-module-data:
        name: Extract Module Information (${{ inputs.module }})
        runs-on: ubuntu-latest
        outputs:
            display_name: ${{ steps.data.outputs.display_name }}
            logo_url: ${{ steps.data.outputs.logo_url }}
            curseforge_id: ${{ steps.data.outputs.curseforge_id }}
            modrinth_id: ${{ steps.data.outputs.modrinth_id }}
            color: ${{ steps.data.outputs.color }}
            artifact_id: ${{ steps.data.outputs.artifact_id }}
        steps:
            - name: Extract Module Data
              id: data
              shell: bash
              run: |
                  echo display_name=$(echo $MODULES_JSON | jq -r .${{ inputs.module }}.display_name) >> $GITHUB_OUTPUT
                  echo logo_url=$(echo $MODULES_JSON | jq -r .${{ inputs.module }}.logo_url) >> $GITHUB_OUTPUT
                  echo curseforge_id=$(echo $MODULES_JSON | jq -r .${{ inputs.module }}.curseforge_id) >> $GITHUB_OUTPUT
                  echo modrinth_id=$(echo $MODULES_JSON | jq -r .${{ inputs.module }}.modrinth_id) >> $GITHUB_OUTPUT
                  echo color="$(($(echo $MODULES_JSON | jq -r .${{ inputs.module }}.color)))" >> $GITHUB_OUTPUT
                  echo artifact_id=$(echo $MODULES_JSON | jq -r .${{ inputs.module }}.artifact_id) >> $GITHUB_OUTPUT
              env:
                  MODULES_JSON: ${{ format('{0}', inputs.modules_json) }}

    # Causes too many workflows to be called, removing this trims it by one getting us back within the call limit
    # publish-platforms:
    #     name: Publish to Platforms
    #     needs: extract-module-data
    #     if: success()
    #     uses: ApexStudios-Dev/.github/.github/workflows/_publish-mod-platforms.yml@master
    #     secrets: inherit
    #     with:
    #         version: ${{ inputs.version }}
    #         build_timestamp: ${{ inputs.build_timestamp }}
    #         display_name: ${{ needs.extract-module-data.outputs.display_name }}
    #         logo_url: ${{ needs.extract-module-data.outputs.logo_url }}
    #         color: ${{ needs.extract-module-data.outputs.color }}
    #         release_type: ${{ inputs.release_type }}
    #         artifact_id: ${{ needs.extract-module-data.outputs.artifact_id }}
    #         curseforge_id: ${{ needs.extract-module-data.outputs.curseforge_id }}
    #         modrinth_id: ${{ needs.extract-module-data.outputs.modrinth_id }}

    # Basically exact copy from 'ApexStudios-Dev/.github/.github/workflows/_publish-mod-platforms.yml'
    # Should be kept inline with upstream
    publish-curseforge:
        name: Publish to CurseForge
        needs: extract-module-data
        uses: ApexStudios-Dev/.github/.github/workflows/_publish-curseforge.yml@master
        if: needs.extract-module-data.outputs.curseforge_id
        secrets: inherit
        with:
            display_name: ${{ needs.extract-module-data.outputs.display_name }}
            version: ${{ inputs.version }}
            release_type: ${{ inputs.release_type }}
            artifact_id: ${{ needs.extract-module-data.outputs.artifact_id }}
            curseforge_id: ${{ needs.extract-module-data.outputs.curseforge_id }}

    publish-modrinth:
        name: Publish to Modrinth
        needs: extract-module-data
        uses: ApexStudios-Dev/.github/.github/workflows/_publish-modrinth.yml@master
        if: needs.extract-module-data.outputs.modrinth_id
        secrets: inherit
        with:
            display_name: ${{ needs.extract-module-data.outputs.display_name }}
            version: ${{ inputs.version }}
            release_type: ${{ inputs.release_type }}
            artifact_id: ${{ needs.extract-module-data.outputs.artifact_id }}
            modrinth_id: ${{ needs.extract-module-data.outputs.modrinth_id }}

    notify-discord:
        name: Send Announcement to Discord
        needs: [ extract-module-data, publish-curseforge, publish-modrinth ]
        if: success()
        runs-on: ubuntu-latest
        steps:
            - name: Send Announcement to Discord
              uses: ApexStudios-Dev/.github/actions/discord-version-notify@master
              with:
                  webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  display_name: ${{ needs.extract-module-data.outputs.display_name }}
                  version: ${{ inputs.version }}
                  logo_url: ${{ needs.extract-module-data.outputs.logo_url }}
                  color: ${{ needs.extract-module-data.outputs.color }}
                  build_timestamp: ${{ inputs.build_timestamp }}
                  curseforge_url: ${{ needs.publish-curseforge.outputs.curseforge_download }}
                  modrinth_url: ${{ needs.publish-modrinth.outputs.modrinth_download }}
