name: Build PR

on:
    pull_request:
        types:
            - synchronize
            - opened
            - ready_for_review
            - reopened

jobs:
    build-pr:
        name: Build PR
        runs-on: apexstudios
        steps:
            - name: Checkout Repository
              id: checkout
              uses: ApexStudios-Dev/.github/actions/checkout@master

            - name: Setup Java
              uses: ApexStudios-Dev/.github/actions/setup-java@master

            - name: Setup Gradle
              uses: ApexStudios-Dev/.github/actions/setup-gradle@master

            - name: Build with Gradle
              run: ./gradlew :publishModulesToPrivateMaven
              env:
                  VERSION: ${{ steps.checkout.outputs.version }}
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
