name: Build PRs

on:
    pull_request:
        types:
            - synchronize
            - opened
            - ready_for_review
            - reopened

jobs:
    get-vars:
        name: Get Variables
        runs-on: apexstudios
        outputs:
            version: ${{ steps.version.outputs.version }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - name: Determine version
              uses: paulhatch/semantic-version@v5.4.0
              id: version
              with:
                  change_path: "./"
                  version_format: "${major}.${minor}.${patch}"
                  search_commit_body: true
                  bump_each_commit: true

    build:
        needs: [ get-vars ]
        uses: ./.github/workflows/_build.yml
        secrets: inherit
        with:
            java_version: 17
            java_vendor: temurin
            version: ${{ needs.get-vars.outputs.version }}
