name: Check Local Changes

on:
  pull_request_target:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened

jobs:
  check-local-changes:
    name: Check Local Changes
    runs-on: apexstudios
    steps:
      - name: Checkout Repository
        id: checkout
        uses: ApexStudios-Dev/.github/actions/checkout@master

      - name: Setup Java
        uses: ApexStudios-Dev/.github/actions/setup-java@master

      - name: Setup Gradle
        uses: ApexStudios-Dev/.github/actions/setup-gradle@master

      - name: Generate Data
        run: ./gradlew :runData :runNordicData :runVenthyrData :runDunmerData :runNecrolordData :runBoneData :runRoyalData
        env:
          VERSION: ${{ steps.checkout.outputs.version }}

      # This is needed otherwise the 'git status' below reports as 'gradlew' being changed
      # Tried running 'git update-index --chmod=+x ./gradlew' to have perms tracked but this did not work
      - name: Mark Gradle as not Executable
        if: always()
        run: chmod -x ./gradlew

      - name: Check no local changes are present
        run: |
          git status
          if [ -n "$(git status --porcelain)" ]; then exit 1; fi
