name: Check Local Changes

on:
  pull_request:
    types:
      - synchronize
      - opened

permissions:
  actions: write
  checks: write
  pull-requests: write
  contents: read

jobs:
  determine-changes:
    name: Determine changes
    runs-on: ubuntu-latest
    outputs:
      main-changed: ${{ steps.changes.outputs.main }}
      nordic-changed: ${{ steps.changes.outputs.nordic }}
      venthyr-changed: ${{ steps.changes.outputs.venthyr }}
      bone-changed: ${{ steps.changes.outputs.bone }}
      dunmer-changed: ${{ steps.changes.outputs.dunmer }}
      necrolord-changed: ${{ steps.changes.outputs.necrolord }}
      royal-changed: ${{ steps.changes.outputs.royal }}
      decorations-changed: ${{ steps.changes.outputs.decorations }}
    steps:
      - name: Determine changes
        id: changes
        uses: dorny/paths-filter@v4.0.1
        with:
          base: 26.1/main
          filters: |
            main: [ 'src/**' ]
            nordic: [ 'nordic/src/**' ]
            venthyr: [ 'venthyr/src/**' ]
            bone: [ 'bone/src/**' ]
            dunmer: [ 'dunmer/src/**' ]
            necrolord: [ 'necrolord/src/**' ]
            royal: [ 'royal/src/**' ]
            decorations: [ 'decorations/src/**' ]

  check-local-changes-main:
    name: Check Local Changes (Main)
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.main-changed == 'true' }}
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 25
      java-vendor: temurin
      use-self-runner: false
      unmark-gradlew-exec: false

  check-local-changes-nordic:
    name: Check Local Changes (Nordic)
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.nordic-changed == 'true' }}
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 25
      java-vendor: temurin
      use-self-runner: false
      data-task: ':nordic:runData'
      unmark-gradlew-exec: false

  check-local-changes-venthyr:
    name: Check Local Changes (Venthyr)
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.venthyr-changed == 'true' }}
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 25
      java-vendor: temurin
      use-self-runner: false
      data-task: ':venthyr:runData'
      unmark-gradlew-exec: false

  check-local-changes-bone:
    name: Check Local Changes (Bone)
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.bone-changed == 'true' }}
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 25
      java-vendor: temurin
      use-self-runner: false
      data-task: ':bone:runData'
      unmark-gradlew-exec: false

  check-local-changes-dunmer:
    name: Check Local Changes (Dunmer)
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.dunmer-changed == 'true' }}
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 25
      java-vendor: temurin
      use-self-runner: false
      data-task: ':dunmer:runData'
      unmark-gradlew-exec: false

  check-local-changes-necrolord:
    name: Check Local Changes (Necrolord)
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.necrolord-changed == 'true' }}
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 25
      java-vendor: temurin
      use-self-runner: false
      data-task: ':necrolord:runData'
      unmark-gradlew-exec: false

  check-local-changes-royal:
    name: Check Local Changes (Royal)
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.royal-changed == 'true' }}
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 25
      java-vendor: temurin
      use-self-runner: false
      data-task: ':royal:runData'
      unmark-gradlew-exec: false

  check-local-changes-decorations:
    name: Check Local Changes (Decorations)
    needs: determine-changes
    if: ${{ needs.determine-changes.outputs.decorations-changed == 'true' }}
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 25
      java-vendor: temurin
      use-self-runner: false
      data-task: ':decorations:runData'
      unmark-gradlew-exec: false