name: Check Local Changes

on:
    pull_request:
        types:
            - synchronize
            - opened
            - ready_for_review
            - reopened

jobs:
    determine-module-changes:
        name: Determine Module Changes
        uses: ./.github/workflows/_module-changes.yml

    check-local-changes:
        name: Check Local Changes
        needs: determine-module-changes
        runs-on: apexstudios
        if: needs.determine-module-changes.outputs.changes != '[]'
        steps:
            - name: Checkout Repository
              id: checkout
              uses: ApexStudios-Dev/.github/actions/checkout@master

            - name: Setup Java
              uses: ApexStudios-Dev/.github/actions/setup-java@master

            - name: Generate Data
              uses: ApexStudios-Dev/.github/actions/run-gradle@master
              with:
                  setup: true
                  tasks: :generateModulesData
              env:
                  VERSION: ${{ steps.checkout.outputs.version }}
                  DATA_MODULES: ${{ join(fromJSON(needs.determine-module-changes.outputs.changes)) }}

            - name: Check no local changes are present
              shell: bash
              run: |
                git status
                if [ -n "$(git status --porcelain)" ]; then exit 1; fi
