name: Publish

on:
    push:
        branches: [ "**/main" ]
        paths: [ "**/src/**" ]

permissions:
    contents: read
    pull-requests: read

jobs:
    determine-module-changes:
        name: Determine Module Changes
        runs-on: ubuntu-latest
        outputs:
            changes: ${{ steps.changes.outputs.changes }}
        steps:
            - name: Checkout Repository
              uses: ApexStudios-Dev/.github/actions/checkout@master

            - name: Determine module changes
              uses: dorny/paths-filter@v3
              id: changes
              with:
                  # base: HEAD # Uncomment for ACT testing
                  filters: |
                      main: [ 'src/**' ]
                      nordic: [ 'nordic/**' ]
                      venthyr: [ 'venthyr/**' ]
                      bone: [ 'bone/**' ]
                      dunmer: [ 'dunmer/**' ]
                      necrolord: [ 'necrolord/**' ]
                      royal: [ 'royal/**' ]
                      decorations: [ 'decorations/**' ]

    publish:
        name: Publish
        needs: determine-module-changes
        uses: ./.github/workflows/_publish-modules.yml
        secrets: inherit
        with:
            modules: ${{ needs.determine-module-changes.outputs.changes }}
            release_type: alpha
            is_manual: false
