name: Test PR

on:
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened

permissions:
  contents: read
  pull-requests: read

jobs:
  generate-vars:
    name: Generate Vars
    uses: ApexStudios-Dev/.github/.github/workflows/_generate-vars.yml@master
    secrets: inherit

  generate-tasks:
    name: Generate Tasks
    runs-on: ubuntu-latest
    outputs:
      nordic-changed: ${{ steps.changes.outputs.nordic }}
      venthyr-changed: ${{ steps.changes.outputs.venthyr }}
      bone-changed: ${{ steps.changes.outputs.bone }}
      dunmer-changed: ${{ steps.changes.outputs.dunmer }}
      necrolord-changed: ${{ steps.changes.outputs.necrolord }}
      royal-changed: ${{ steps.changes.outputs.royal }}
      publish: ${{ steps.tasks.outputs.publish }}
      data: ${{ steps.tasks.outputs.data }}
    steps:
      - name: Determine changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            nordic: [ 'nordic/**' ]
            venthyr: [ 'venthyr/**' ]
            bone: [ 'bone/**' ]
            dunmer: [ 'dunmer/**' ]
            necrolord: [ 'necrolord/**' ]
            royal: [ 'royal/**' ]

      - name: Output tasks
        id: tasks
        run: |
          publishTask=":publishReleasePublicationToApexStudios-PrivateRepository"
          dataTask=":runData"
          
          if [[ "$NORDIC_CHANGED" == "true" ]]; then
            publishTask+=" :publishNordicReleasePublicationToApexStudios-PrivateRepository"
            dataTask+=" :runNordicData"
          fi
          
          if [[ "$VENTHYR_CHANGED" == "true" ]]; then
            publishTask+=" :publishVenthyrReleasePublicationToApexStudios-PrivateRepository"
            dataTask+=" :runVenthyrData"
          fi
          
          if [[ "$BONE_CHANGED" == "true" ]]; then
            publishTask+=" :publishBoneReleasePublicationToApexStudios-PrivateRepository"
            dataTask+=" :runBoneData"
          fi
          
          if [[ "$DUNMER_CHANGED" == "true" ]]; then
            publishTask+=" :publishDunmerReleasePublicationToApexStudios-PrivateRepository"
            dataTask+=" :runDunmerData"
          fi
          
          if [[ "$NECROLORD_CHANGED" == "true" ]]; then
            publishTask+=" :publishNecrolordReleasePublicationToApexStudios-PrivateRepository"
            dataTask+=" :runNecrolordData"
          fi
          
          if [[ "$ROYAL_CHANGED" == "true" ]]; then
            publishTask+=" :publishRoyalReleasePublicationToApexStudios-PrivateRepository"
            dataTask+=" :runRoyalData"
          fi
          
          echo publish="$publishTask" >> "$GITHUB_OUTPUT"
          echo data="$dataTask" >> "$GITHUB_OUTPUT"
        env:
          NORDIC_CHANGED: ${{ steps.changes.outputs.nordic }}
          VENTHYR_CHANGED: ${{ steps.changes.outputs.venthyr }}
          BONE_CHANGED: ${{ steps.changes.outputs.bone }}
          DUNMER_CHANGED: ${{ steps.changes.outputs.dunmer }}
          NECROLORD_CHANGED: ${{ steps.changes.outputs.necrolord }}
          ROYAL_CHANGED: ${{ steps.changes.outputs.royal }}

  build:
    name: Build
    needs: generate-vars
    if: success()
    uses: ApexStudios-Dev/.github/.github/workflows/_build.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      version: ${{ needs.generate-vars.outputs.version }}

  check-local-changes:
    name: Check local changes
    needs: [ generate-vars, generate-tasks ]
    if: success()
    uses: ApexStudios-Dev/.github/.github/workflows/_check-local-changes.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      version: ${{ needs.generate-vars.outputs.version }}
      data-task: ${{ needs.generate-tasks.outputs.data }}

  publish-maven:
    name: Publish Maven
    needs: [ generate-vars, generate-tasks, build, check-local-changes ]
    if: success()
    uses: ApexStudios-Dev/.github/.github/workflows/_publish-maven.yml@master
    secrets: inherit
    with:
      java-version: 21
      java-vendor: temurin
      version: ${{ needs.generate-vars.outputs.version }}
      publish-task: ${{ needs.generate-tasks.outputs.publish }}

  test:
    name: Test Production
    runs-on: apexstudios
    needs: [ generate-vars, generate-tasks, publish-maven ]
    if: success()
    steps:
      - name: Prepare Environment
        run: |
          mkdir mods
          wget -O "mods/apexcore-$APEXCORE_VERSION.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/apexcore/$APEXCORE_VERSION/apexcore-$APEXCORE_VERSION.jar"
          wget -O "mods/fantasyfurniture-${{ needs.generate-vars.outputs.version }}.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/fantasyfurniture/${{ needs.generate-vars.outputs.version }}/fantasyfurniture-${{ needs.generate-vars.outputs.version }}.jar"

          if [[ "$NORDIC_CHANGED" == "true" ]]; then
            wget -O "mods/fantasyfurniture-nordic-${{ needs.generate-vars.outputs.version }}.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/fantasyfurniture-nordic/${{ needs.generate-vars.outputs.version }}/fantasyfurniture-nordic-${{ needs.generate-vars.outputs.version }}.jar"
          fi

          if [[ "$VENTHYR_CHANGED" == "true" ]]; then
            wget -O "mods/fantasyfurniture-venthyr-${{ needs.generate-vars.outputs.version }}.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/fantasyfurniture-venthyr/${{ needs.generate-vars.outputs.version }}/fantasyfurniture-venthyr-${{ needs.generate-vars.outputs.version }}.jar"
          fi

          if [[ "$BONE_CHANGED" == "true" ]]; then
            wget -O "mods/fantasyfurniture-bone-${{ needs.generate-vars.outputs.version }}.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/fantasyfurniture-bone/${{ needs.generate-vars.outputs.version }}/fantasyfurniture-bone-${{ needs.generate-vars.outputs.version }}.jar"
          fi

          if [[ "$DUNMER_CHANGED" == "true" ]]; then
            wget -O "mods/fantasyfurniture-dunmer-${{ needs.generate-vars.outputs.version }}.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/fantasyfurniture-dunmer/${{ needs.generate-vars.outputs.version }}/fantasyfurniture-dunmer-${{ needs.generate-vars.outputs.version }}.jar"
          fi

          if [[ "$NECROLORD_CHANGED" == "true" ]]; then
            wget -O "mods/fantasyfurniture-necrolord-${{ needs.generate-vars.outputs.version }}.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/fantasyfurniture-necrolord/${{ needs.generate-vars.outputs.version }}/fantasyfurniture-necrolord-${{ needs.generate-vars.outputs.version }}.jar"
          fi

          if [[ "$ROYAL_CHANGED" == "true" ]]; then
            wget -O "mods/fantasyfurniture-royal-${{ needs.generate-vars.outputs.version }}.jar" "https://maven.apexstudios.dev/private/dev/apexstudios/fantasyfurniture-royal/${{ needs.generate-vars.outputs.version }}/fantasyfurniture-royal-${{ needs.generate-vars.outputs.version }}.jar"
          fi
        env:
          APEXCORE_VERSION: 21.5.3
          NORDIC_CHANGED: ${{ needs.generate-tasks.outputs.nordic-changed }}
          VENTHYR_CHANGED: ${{ needs.generate-tasks.outputs.venthyr-changed }}
          BONE_CHANGED: ${{ needs.generate-tasks.outputs.bone-changed }}
          DUNMER_CHANGED: ${{ needs.generate-tasks.outputs.dunmer-changed }}
          NECROLORD_CHANGED: ${{ needs.generate-tasks.outputs.necrolord-changed }}
          ROYAL_CHANGED: ${{ needs.generate-tasks.outputs.royal-changed }}

      - name: Test Production Server
        uses: ApexStudios-Dev/.github/actions/test-production-server@master
        with:
          java-version: 21
          java-vendor: temurin
          neoforge-version: 21.5.34-beta
